### PR TITLE
WIP records: handle zone/domain strings with leading/trailing dots

### PR DESCRIPTION
**Pull request by rupa**
* normalizeFQDN func strips any leading or trailing dots from a string
* normalizeFQDN called on zone/domain before writing to state
* normalizeFQDN called on zone/domain before passing to API

WIP for feedback, TODO:
* unit test for normalizeFQDN
* acc tests exercizing normalizeFQDN

### CODE REVIEW

**Comment by sam-caldwell** [comment]
This would work.  

However, I would suggest a defense in depth approach with a complementary fix to the API SDK.  The original error I was seeing was an HTTP/400 from the API.  

But with that said, this is a better solution in that it handles my TF issue in TF and that is all that really matters to me personally.

**Comment by mburtless** [comment]
I have mixed feelings about this.  I see the use, but ultimately this kind of functionality causes the input the user provided to show up as something different in plan or when referring to the attribute in expressions elsewhere.  That can cause surprising behavior for the user.

According to [comments by hashi](https://github.com/hashicorp/terraform-plugin-sdk/issues/164#issuecomment-503800443), `StateFunc` may be deprecated in the future for this reason (it's original intent was around compacting multi-line strings, which 0.12 addresses).

Might be cleaner and more future proof to just implement a validate function to detect trailing dots and put the onus on the user to make sure their input is valid (i.e. by using `replace` as mentioned in [ns1-go #80](https://github.com/ns1/ns1-go/pull/80#issuecomment-555204679)).

Downside is it requires more work for the user, but at least a validation would make it clear _what_ is causing the error before receiving `HTTP 400` from the API.

**Comment by sam-caldwell** [comment]
@mburtless, as a customer and user, this bug cost me several hours of productivity.

First, I had to enter the debugging operation with the assumption that terraform-provider-ns1 is bug free and works as expected.  This means I had to validate my terraform down to the module to ensure the mistake was not mine.

Second, after this, I had to test and finally find issue #80 and the workaround with terraform replace().  This is a 'workaround' for a reason.

My Terraform specifically did not append a zone name to the domain because I knew ACM would do that for me.  But because terraform-provider-ns1 does not match the suffix of the domain string properly (due to the trailing dot (proper grammar in DNS, I might add), NS1 chose to append the zone to a fully qualified domain name...resulting in an HTTP/400 (BAD REQUEST).

My original pull request on the matter was to do the sanitization in the ns1 SDK but it was (appropriately) suggested that the change should go in the terraform module.

To be honest, putting the onus on the user is something I learned never to do, especially when there is a bug involved.

**Comment by mburtless** [comment]
Hi @sam-caldwell - I wasn't trying to minimize the frustration that this issue must have caused or imply that no action should be taken here.  I apologize if that's how my comment came across.  I certainly appreciate the time you had to spend on troubleshooting this and bringing it to our attention.

My intent was merely to bring to everyone's attention that there is a technical concern with the current solution: Terraform core's maintainers have indicated that `StateFunc` was not intended to provide input sanitization and may be deprecated in the future.

To further clarify, the alternative I suggested above was to catch trailing or leading dots with a `ValidateFunc` and throw a clear error to the user indicating the issue, which will keep this sort of thing from wasting much time in the future.  We would clearly need to document the `replace` function that can be used for sanitization within the provider as well.

We did ask for feedback via slack from Terraform core's maintainers on this and they also recommend to use a `ValidateFunc` instead of performing sanitization.

I understand that this is not as painless a solution as performing the sanitization in the provider, but it's the safest solution that Terraform allows us.

**Comment by Zach-Johnson** [comment]
A separate PR adding validation with a `ValidateFunc` has been opened here: https://github.com/terraform-providers/terraform-provider-ns1/pull/97

**Comment by rupa** [comment]
going to close out this PR in favor of #97 (and a couple of doc updates should be showing up in #98)

**Pull request closed without merging**
